<form class="generic-form" method="post">
      <fieldset>
          <legend>Connectez-vous</legend>
          <ul>
              <li>
                  <label for="email">Email</label>
                  <input type="email" id="email" name="email">
              </li>
              <li>
                  <label for="password">Password</label>
                  <input type="password" id="password" name="password">
              </li>
          </ul>
          <button class="button button-primary" type="submit">Valider</button>
      </fieldset>
</form>